name: Python application lint and unittest

on: [push, pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build docker image
      run: docker build -t cs229 .
      
    - name: Run linting in the donctainer
      run: docker run cs229 ruff .
    
    - name: Run tests in the container
      run: docker run cs229 pytest
