name: Build

on:
  push:
    paths:
      - algorithms/**
      - data/**
      - tests/**
      - .github/**
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build docker image
      run: docker build -t cs229 .
      
    - name: Run tests and generate coverage
      run: docker run --name mlalgs cs229 coverage run -m pytest
    - name: Run coveralls
      run: docker run -e COVERALLS_REPO_TOKEN=${{ secrets.COVERALL_REPO_KEY }} cs229 /bin/bash -c "coverage run -m pytest && coveralls"
      
    - name: Copy coverage file
      run: docker cp mlalgs:/usr/src/app/.coverage ./.coverage
      
    - name: Run formatting
      run: docker run cs229 ruff format --check .
      
    - name: Run linting
      run: docker run cs229 ruff .
      
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
            
    
