name: Build

on:
  push:
    paths:
      - algorithms/**
      - data/**
      - tests/**
      - .github/**
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build docker image
      run: docker build -t cs229 .

    - name: Run formatting
      run: docker run cs229 ruff format --check .
      
    - name: Run linting
      run: docker run cs229 ruff .
    
    - name: Run tests and generate coverage
      run: |
        mkdir -p coverage_data
        docker run -v $(pwd)/coverage_data:/usr/src/app cs229 sh -c "coverage run -m pytest && ls -a"
        ls -l ./coverage_data


    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
            
    
