name: Build

on:
  push:
    paths:
      - algorithms/**
      - data/**
      - tests/**
      - .github/**
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build docker image
      run: docker build -t cs229 .

    - name: Run formatting in the container
      run: docker run cs229 ruff format --check .
      
    - name: Run linting in the container
      run: docker run cs229 ruff .
    
    - name: Run tests in the container
      run: docker run cs229 pytest
      
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
            
    
