name: Build

on:
  push:
    paths:
      - algorithms/**
      - data/**
      - tests/**
      - .github/**
jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build docker image
      run: docker build -t cs229 .

    - name: Run formatting
      run: docker run cs229 ruff format --check .
      
    - name: Run linting
      run: docker run cs229 ruff .
    
    - name: Run tests
      run: docker run cs229 coverage run -m pytest
    - name: list files
      run: docker run cs229 ls -a

    - name: Run coverage check
      run: docker run cs229 coverage lcov

   
      
    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2.2.3
            
    
